name: OWASP Dependency-Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "cipro_backend"
          path: './package-lock.json'
          format: 'JSON'
          out: './dependency-check-report.json'

      - name: Send JSON Report to Backend via GitHub API
        run: |
          curl -X POST http://localhost:3001/reports/owasp \
           -H "Content-Type: application/json" \
           --data-binary @dependency-check-report.json
